# -*- coding: utf-8 -*-
"""LDP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XpxIk7JbTbmOOaEDPenLJP2ehu37YOs_

#Aula 6 Pandas
"""

import pandas as pd
import numpy as np

print('✅ Bibliotecas importadas com sucesso!')
print(f'Versão do Pandas: {pd.__version__}')

dados = {
    'Nome':   ['Ana', 'Bruno', 'Carlos', 'Diana', 'Eduardo'],
    'Idade':  [23, 35, 28, 41, 19],
    'Cidade': ['São Paulo', 'Rio de Janeiro', 'Belo Horizonte', 'São Paulo', 'Curitiba'],
    'Salário':[4500, 8200, 6100, 9300, 2800]
}

df = pd.DataFrame(dados)
display(df)

linhas = [
    ['Produto A', 'Eletrônicos', 1500.00],
    ['Produto B', 'Roupas',        89.90],
    ['Produto C', 'Eletrônicos',  349.00],
]

df_produtos = pd.DataFrame(linhas, columns=['Produto', 'Categoria', 'Preço'])
print(df_produtos)

# Vamos usar o df de pessoas para os exemplos seguintes
print('=== Primeiras linhas ===')
print(df.head())       # mostra as 5 primeiras linhas por padrão

print(df.tail())

print('=== Dimensões (linhas x colunas) ===')
print(df.shape)

print('=== Informações gerais ===')
df.info()

print('=== Estatísticas descritivas ===')
print(df.describe().round(2))   # média, desvio padrão, mín, máx, etc.

print('=== Nomes das colunas ===')
print(df.columns.tolist())

print('\n=== Tipos de cada coluna ===')
print(df.dtypes)

print(df['Nome'])

print(df[['Nome', 'Salário']])

print('Linha 0 (primeira):')
print(df.iloc[0])              # primeira linha

print('\nLinhas 1 a 3:')
print(df.iloc[1:4])            # linhas 1, 2 e 3

print('\nÚltima linha:')
print(df.iloc[-1])

# Selecionar linha de índice 2 e apenas as colunas Nome e Cidade
print(df.loc[2, ['Nome', 'Cidade']])

print()

# Selecionar várias linhas e colunas
print(df.loc[0:2, 'Nome':'Cidade'])

# Pessoas com mais de 25 anos
filtro = df['Idade'] > 25
print('Máscara booleana:')
print(filtro)

print('\nResultado filtrado:')
print(df[filtro])

# Forma direta (sem variável intermediária)
print(df[df['Salário'] >= 6000])

# Múltiplas condições: use & (E) e | (OU)
# ⚠️ Cada condição deve estar entre parênteses!

# Pessoas com mais de 25 anos E salário acima de 5000
print(df[(df['Idade'] > 25) & (df['Salário'] > 5000)])

# Filtrando por texto: cidade igual a São Paulo
print(df[df['Cidade'] == 'São Paulo'])

cidades_sul = ['Curitiba', 'Porto Alegre', 'Florianópolis']
print(df[df['Cidade'].isin(cidades_sul)])

# Adicionando uma nova coluna calculada
df['Salário Anual'] = df['Salário'] * 12
print(df)

# Adicionando coluna com valor fixo
df['País'] = 'Brasil'
print(df.head())

# Usando .apply() para criar coluna com lógica condicional
def classificar_salario(salario):
    if salario < 4000:
        return 'Baixo'
    elif salario < 7000:
        return 'Médio'
    else:
        return 'Alto'

df['Faixa Salarial'] = df['Salário'].apply(classificar_salario)
print(df[['Nome', 'Salário', 'Faixa Salarial']])

# Removendo colunas com .drop()
df_simplificado = df.drop(columns=['País', 'Salário Anual'])
print(df_simplificado)

# Simulando a leitura de um CSV (criamos o conteúdo diretamente)
from io import StringIO

csv_simulado = """Nome,Nota1,Nota2,Nota3
Alice,8.5,7.0,9.0
Bob,6.0,5.5,7.5
Carla,9.5,10.0,8.0
Daniel,4.0,6.5,5.0
"""

df_notas = pd.read_csv(StringIO(csv_simulado))
print(df_notas)

# Em um caso real seria:
# df_notas = pd.read_csv('meu_arquivo.csv')

"""# Aula 5"""

lista = [3,7,9,12,7]
print(lista)

carros = ['fiat', 'gol', 'uno']
print(carros[1])
carros[1] = 'porsche'
print(carros)

for carro in carros:
  print(carro)

frutas = ['maça', 'banana', 'roma', 'uva', 'carambola']
print(frutas, frutas[0], frutas[4])

numeros = [1, 5 , 7 , 10, 23]
for i in numeros:
  print(i)
print(sum(numeros))

contador = 0
num = [1, 5, 31, 2 ,21 ,3]
for i in num:
  if i > 10:
    contador += 1
print(contador)

lista = [1, 4, 5, 6 ,7]
x = 0
for i in lista:
  if i > x:
    x = i
print(x)

par = []
contador = 0
num = [1, 5, 31, 2 ,21 ,3, 23, 1]
for i in num:
  if i % 2 == 0:
    par.append(i)
    contador += 1
print(par, contador)

"""# Aula 4"""

def saudacao():
  print('hello!')
saudacao()

def soma(n1,n2):
  return n1 + n2
resultado = soma(2,3)
print(resultado)
print(soma(4,8))

def saudacao():
    nome = input('Digite seu nome: ')
    print(f'Olá, {nome}!')

saudacao()

def soma(a, b):
 return a + b
a = int(input('digite o valor de a'))
b = int(input('digite o valor de b'))
print(soma(a,b))

def par_ou_impar(n):
    n = int(input('digite um numero'))
    if n % 2 == 0:
        return "Par"
    else:
        return "Ímpar"

print(par_ou_impar(n))

def dobro(n):
  return n * 2
n = float(input('digite um numero: '))
print(dobro(n))

def maior():
  a = int(input('digite o valor de a'))
  b = int(input('digite o valor de b'))
  if a > b:
    return a
  elif a < b:
    return b
  else:
    return a
print(maior())

def maior():
  a = int(input('digite o valor de a: '))
  b = int(input('digite o valor de b: '))
  c = int(input('digite o valor de c: '))
  if a >= b and a >= c:
    return a
  elif b >= a and b >= c:
    return b
  else:
    return c
print(maior())

idade = int(input('idade'))
def ident(idade):
  if idade >= 18:
    print('você é maior de idade')
  else:
    print('voce é de menor')
ident(idade)

def calculadora(a, b, operacao):
  if operacao == 'soma':
    return a + b
  elif operacao == 'subtrair':
    return a - b
  elif operacao == 'multiplicar':
    return a * b
  else:
    return a / b
operacao = input('digite o quer fazer(soma/subtrair/multiplicar/dividir)')
a = int(input('Digite o número a: '))
b = int(input('Digite o número b: '))

print(calculadora(a , b , operacao))

def fatorial(n):
    fat = 1
    for x in range(1, n+1):
      fat = fat * x
    return fat
n = int(input('digite um valor'))
print(fatorial(n))

def area(altura, largura):
  return (altura * largura)/ 2
altura = int(input('digite o valor da altura'))
largura = int(input('digite o valor da largura'))
area(altura,largura)

def cel_para_f():
   c = float(input('digite o valor em celcius'))
   return (c*9/5)+32
print(cel_para_f(), 'esse é o valor em faren')

def conjunto(a):
  a = int(input('digite um valor'))
  if a > 0:
    return 'positivo'
  elif a < 0:
    return'negativo'
  else:
    return 'zero'
print('O seu numero é', conjunto(a) )

def primerio(a, b):
  x = -b/a
  return x
a = int(input('digite o valor de a'))
b = int(input('digite o valor de b'))

print(primerio(a, b))

def calculadora(a, b, operacao):
  try:
    if operacao == 'soma':
      return a + b
    elif operacao == 'subtrair':
      return a - b
    elif operacao == 'multiplicar':
      return a * b
    else:
        return a / b
  except:
    print("Cálculo inválido")

try:
  operacao = input('digite o quer fazer(soma/subtrair/multiplicar/dividir)')
  a = int(input('Digite o número a: '))
  b = int(input('Digite o número b: '))
except ValueError:
  print("Valor inválido")

calculadora(a , b , operacao)

def tipo_triangulo(a, b ,c):
  if a = b = c:

"""# Aula 3"""

i = 1
soma = 0
while i <= 100:
 soma = soma + i
 i = i + 1
print(soma)

numero = 10

while numero >= 1:
    print(numero)
    numero -= 1

numero = int(input("Digite um número: "))
i = 1

while i <= 10:
    resultado = numero * i
    print(numero, "x", i, "=", resultado)
    i += 1

i = 0
while i <= 10:
  print(i)
  i += 1

i = 8
while True:
  a = int(input("Digite um valor"))
  if a == i:
   print('voce acertou')
   break
  else:
    print('voce errou')

y = 0
for x in range(10):
  a = int(input("Digite um valor"))
  if a > y:
    y = a
print(y)

soma = 0
while True:
  a = int(input("Digite um valor (digite 0 para parar)"))
  soma += a

  if a == 0:
    b = int(input("quantos valores voce digitou?"))
    media = soma / b
    break
print(media)

# Lista para armazenar os números positivos
positivos = []

# Laço que pede 10 números
for i in range(10):
    num = int(input("Digite um número: "))
    if num > 0:
        positivos.append(num)  # adiciona apenas os positivos

# Mostra todos os positivos digitados
print("Números positivos digitados:", positivos)

"""# Aula 2"""

numero = int(input("Digite um número:"))
if numero > 0:
  print('o numero é positivo')
elif numero < 0:
  print('o numero é negativo')
else:
  print('o numero é zero')

a = 'sim'
b = 'não'
idade = int(input('Digite sua idade:'))
carteira = input('Você possui carteira de motorista?')
if idade >= 18 and carteira == a:
  print('você pode dirigir')
else:
  print('você não pode dirigir')

A = 9 / 3 == 3 * 3
B = 2 * 3 – 1 >= 8

if A == True:
  print('A é verdadeira')
else:
  print('A é falsa')

A = 5*4<4+3
if A == True:
  print('A é verdadeira')
else:
  print('A é falsa')

import string
pode = 'AlAaAzAaArAeAnAtAoA'
carte =''.join(ch for ch in pode if ch not in string.ascii_uppercase)
print(carte)

"""#Aula 1"""

numero = int(input("Digite um número:"))
antecessor = numero - 1
sucessor = numero + 1
print('o antecessor do seu numero é: ' + str(antecessor) + ' e o sucessor do seu numero é: ' + str(sucessor))

numero = int(input("Digite um número:"))
dobro = numero * 2
triplo = numero * 3
raiz = numero ** 0.5
print('o dobro do seu numero é:' + str(dobro))
print('o dobro do seu numero é:' + str(triplo))
print('o dobro do seu numero é:' + str(round(raiz)))

nota1 = float(input("Digite a primeira nota:"))
nota2 = float(input('Digite a segunda nota:'))
nota3 = float(input('Digite a terceira nota:'))
media = (nota1 + nota2 + nota3) / 3
if media >= 6:
  print('você passou!!!!')
else:
  print('você não passou!!!!')

valor_produto = float(input('fale o valor do produto:'))
forma_pagamento = str(input('qual forma de pagamento?'))

if forma_pagamento == str("pix"):
  print('seu produto possui um desconto de 10% ficando no total:' + str(valor_produto - valor_produto * 0.1) + (' vai ser no credito ou no debito?'))
elif valor_produto >= 100:
  print('seu produto possui um desconto de 5% ficando no total: ' + str(valor_produto - valor_produto * 0.05) + (' vai ser no credito ou no debito?'))
else:
  print('não podemos dar desconto no produto vai ser pobrinho em outro lugar!')